<?php

return [
    'sections' => [
        [
            'slug' => 'point-of-sale',
            'nav_label' => 'Checkout',
            'eyebrow' => 'Point of sale',
            'title' => 'Checkout that keeps the line moving and every total accurate.',
            'overview' => 'SkelApp gives your cashier one clear flow for scanning, searching, pricing, discounting, and closing a sale. It is built for busy counters where speed matters, but without losing the detail you need for reporting later.',
            'note_label' => 'Built for',
            'note_value' => 'Fast-moving shops, split payments, receipt printing, and daily cashier reconciliation.',
            'image' => 'assets/CHECKOUTPOS.png',
            'image_alt' => 'SkelApp point of sale checkout screen',
            'match_terms' => ['point of sale', 'pos', 'checkout', 'fast checkout', 'split billing', 'payments'],
            'capabilities' => [
                ['title' => 'Search, scan, or tap products', 'body' => 'Cashiers can find items by name, SKU, barcode, or category so queues keep moving even when the basket is large.'],
                ['title' => 'Flexible payments on one sale', 'body' => 'Record cash, mobile money, transfer, or mixed payments on the same transaction without manual reconciliation later.'],
                ['title' => 'Discounts and price overrides', 'body' => 'Apply line-level discounts, order discounts, or approved overrides while still keeping a clean audit trail.'],
                ['title' => 'Receipts everywhere', 'body' => 'Print instantly on a thermal printer or share a receipt digitally when the customer prefers a paperless copy.'],
                ['title' => 'Offline-ready selling', 'body' => 'Continue recording sales when connectivity is unstable, then sync the data back when the connection returns.'],
            ],
        ],
        [
            'slug' => 'catalog-and-products',
            'nav_label' => 'Products',
            'eyebrow' => 'Catalog & pricing',
            'title' => 'Keep products, categories, and pricing clean as your catalog grows.',
            'overview' => 'Your POS becomes much faster when products are structured properly. SkelApp helps you organise items in a way that makes sense for your team, whether you stock a few hundred lines or a fast-changing retail catalog.',
            'note_label' => 'Best for',
            'note_value' => 'Shops with many SKUs, variants, seasonal pricing, or multiple product categories.',
            'image' => 'assets/Moc-tab.webp',
            'image_alt' => 'SkelApp product catalog on a tablet',
            'match_terms' => ['catalog', 'products', 'product catalog', 'categories', 'pricing', 'items'],
            'capabilities' => [
                ['title' => 'Category-first organisation', 'body' => 'Group items by department, shelf type, supplier line, or any other structure that helps staff find products faster.'],
                ['title' => 'Clear pricing controls', 'body' => 'Set selling prices confidently and keep them consistent across your team, branches, and daily checkout flow.'],
                ['title' => 'Faster product lookup', 'body' => 'Well-structured products shorten training time for new cashiers and reduce mistakes during peak trading hours.'],
                ['title' => 'Room for variants and details', 'body' => 'Track different sizes, pack types, or related item attributes without turning your catalog into a spreadsheet mess.'],
                ['title' => 'Bulk-friendly maintenance', 'body' => 'Update products in batches when you need to clean up categories, pricing, or stock setup at scale.'],
            ],
        ],
        [
            'slug' => 'inventory-and-stock',
            'nav_label' => 'Inventory',
            'eyebrow' => 'Stock control',
            'title' => 'Track stock in real time so the shelf count matches the system count.',
            'overview' => 'SkelApp connects selling, restocking, and stock visibility in one flow. Every sale updates inventory automatically, giving owners and managers a clearer picture of what is moving, what is low, and what needs action next.',
            'note_label' => 'Operational value',
            'note_value' => 'Fewer stockouts, fewer manual count surprises, and better restocking decisions across every branch.',
            'image' => 'assets/STOCKLIST.png',
            'image_alt' => 'SkelApp stock list and inventory screen',
            'match_terms' => ['inventory', 'stock', 'stock list', 'low stock', 'suppliers', 'purchases'],
            'capabilities' => [
                ['title' => 'Live inventory updates', 'body' => 'Every completed sale adjusts item quantities automatically, so your stock position stays current through the day.'],
                ['title' => 'Low-stock visibility', 'body' => 'Spot fast-moving items before they run out and restock with better timing instead of reacting late.'],
                ['title' => 'Branch-aware stock tracking', 'body' => 'See what is available at each outlet so you can transfer or reorder with more confidence.'],
                ['title' => 'Restocks and supplier deliveries', 'body' => 'Log incoming stock cleanly and compare what arrived with what was expected from a supplier.'],
                ['title' => 'Fewer manual corrections', 'body' => 'Because sales and stock are connected, you spend less time fixing mismatched figures at the end of the week.'],
            ],
        ],
        [
            'slug' => 'customers-and-loyalty',
            'nav_label' => 'Customers',
            'eyebrow' => 'CRM & loyalty',
            'title' => 'Turn repeat shoppers into visible customer relationships, not guesswork.',
            'overview' => 'SkelApp helps you see who is buying, what they buy, and how often they come back. That gives you a stronger base for follow-up, better service, and more deliberate loyalty building over time.',
            'note_label' => 'Use it for',
            'note_value' => 'Retailers who want stronger repeat business, customer history, and cleaner relationship tracking.',
            'image' => 'assets/crm.webp',
            'image_alt' => 'SkelApp customer management view',
            'match_terms' => ['customers', 'crm', 'loyalty', 'repeat', 'best customers'],
            'capabilities' => [
                ['title' => 'Customer history on record', 'body' => 'See previous purchases and buying behaviour so staff can serve returning customers with better context.'],
                ['title' => 'Identify your best buyers', 'body' => 'Quickly spot customers who purchase often or spend more, making it easier to nurture long-term value.'],
                ['title' => 'Cleaner service follow-up', 'body' => 'A visible customer record makes it easier to handle questions, repeat orders, or after-sales support.'],
                ['title' => 'Better retention decisions', 'body' => 'Instead of guessing which buyers matter most, you can act on actual transaction history.'],
                ['title' => 'One shared customer view', 'body' => 'Teams work from the same customer information instead of scattered notes or memory.'],
            ],
        ],
        [
            'slug' => 'staff-and-branches',
            'nav_label' => 'Team & branches',
            'eyebrow' => 'Access & accountability',
            'title' => 'Give every staff member the right access while keeping owners in control.',
            'overview' => 'Retail operations run better when roles are clear. SkelApp helps you manage who can sell, discount, refund, view reports, or edit products, while still keeping a clean owner-level overview across the business.',
            'note_label' => 'Made for',
            'note_value' => 'Managers handling multiple attendants, branch comparisons, and permission-sensitive workflows.',
            'image' => 'assets/attendants.webp',
            'image_alt' => 'Retail staff using SkelApp',
            'match_terms' => ['team', 'staff', 'branches', 'attendants', 'permissions', 'control'],
            'capabilities' => [
                ['title' => 'Role-based permissions', 'body' => 'Separate cashier, manager, and owner access so each person sees the tools relevant to their job.'],
                ['title' => 'Cashier-level accountability', 'body' => 'Track who processed which sale, discount, refund, or correction when reviewing daily operations.'],
                ['title' => 'Branch-by-branch oversight', 'body' => 'Compare branch activity without merging everything into one unclear total.'],
                ['title' => 'Safer approvals', 'body' => 'Sensitive actions can be limited to the right people, reducing accidental changes on the shop floor.'],
                ['title' => 'Simpler team onboarding', 'body' => 'A cleaner interface and structured roles help new staff get productive faster.'],
            ],
        ],
        [
            'slug' => 'reports-and-profits',
            'nav_label' => 'Reports',
            'eyebrow' => 'Analytics & profit clarity',
            'title' => 'Know what you sold, what you spent, and what you actually made.',
            'overview' => 'SkelApp reporting is designed for owners who want quick clarity, not accounting complexity. The goal is simple: open the dashboard and understand how the business is performing without waiting for manual summaries.',
            'note_label' => 'What you see',
            'note_value' => 'Sales trends, payment mix, best sellers, branch performance, and day-to-day profit visibility.',
            'image' => 'assets/DASHBOARD.png',
            'image_alt' => 'SkelApp reporting dashboard',
            'match_terms' => ['profits', 'profit', 'reports', 'analytics', 'cashflow', 'dashboard'],
            'capabilities' => [
                ['title' => 'Daily sales visibility', 'body' => 'Review revenue quickly and see whether the business is tracking above or below expectations.'],
                ['title' => 'Best-seller awareness', 'body' => 'Spot which products deserve faster reorders and which items are tying up cash on the shelf.'],
                ['title' => 'Payment method breakdowns', 'body' => 'Separate cash, mobile money, transfer, and other collections for cleaner reconciliation.'],
                ['title' => 'Profit-minded decision support', 'body' => 'Move away from gut feel and use clearer numbers when pricing, restocking, or staffing.'],
                ['title' => 'Manager and branch comparisons', 'body' => 'See performance by cashier or location so you know where to investigate, improve, or repeat success.'],
            ],
        ],
        [
            'slug' => 'mobile-and-devices',
            'nav_label' => 'Devices',
            'eyebrow' => 'Mobile & hardware',
            'title' => 'Run the same retail system on a phone, tablet, or full counter setup.',
            'overview' => 'You do not need to start with expensive hardware to use SkelApp properly. Begin on the device you already have, then expand into printers, scanners, tablets, or a complete POS counter when the business is ready.',
            'note_label' => 'Deployment options',
            'note_value' => 'Phone-only selling, tablet checkout, portable line-busting, or full countertop POS hardware.',
            'image' => 'assets/PosSystemRegister.webp',
            'image_alt' => 'SkelApp hardware and device setup',
            'match_terms' => ['hardware', 'mobile', 'devices', 'terminal', 'tablet', 'phone'],
            'capabilities' => [
                ['title' => 'Works on existing devices', 'body' => 'Start on a supported phone or tablet first, which lowers the barrier to adopting a proper POS workflow.'],
                ['title' => 'Add hardware when ready', 'body' => 'Pair printers, scanners, cash drawers, or a full terminal setup as your operation grows.'],
                ['title' => 'Consistent experience across screens', 'body' => 'Sales, stock, and customer data stay connected even when the team uses different device types.'],
                ['title' => 'Flexible selling environments', 'body' => 'Use the same system at the main counter, on the shop floor, or at temporary selling points during busy periods.'],
                ['title' => 'Built for practical rollout', 'body' => 'You can deploy gradually instead of replacing every device in the business at once.'],
            ],
        ],
    ],
];
