<?php

return [
    'hero' => [
        'eyebrow' => 'SkelApp integrations',
        'title' => "Connect SkelApp\nto the tools you already use",
        'subtitle' => 'Sync accounting, customer messaging, receipts, alerts and bulk SMS from one connected POS workflow.',
        'image' => 'assets/HeroImage.webp',
        'primary_label' => 'Explore integrations',
        'secondary_label' => 'Talk to an expert',
    ],

    'categories' => [
        [
            'title' => 'Accounting & finance',
            'subtitle' => 'Keep sales, taxes, payments and business reports aligned with your accounting stack.',
            'slugs' => ['zoho-books', 'xero', 'quickbooks', 'sage'],
        ],
        [
            'title' => 'Messaging & notifications',
            'subtitle' => 'Reach customers where they already are with WhatsApp, SMS alerts and campaign messaging.',
            'slugs' => ['whatsapp', 'notify-africa-bulksms'],
        ],
    ],

    'faq' => [
        ['q' => 'Can SkelApp connect to my accounting software?', 'a' => 'Yes. SkelApp can connect with accounting platforms such as Zoho Books, Xero, QuickBooks and Sage so sales and payment records stay easier to reconcile.'],
        ['q' => 'Do integrations need custom development?', 'a' => 'Some integrations can be configured directly, while others may need a short setup with our team depending on your workflow, branch setup and data fields.'],
        ['q' => 'Can I use more than one integration at the same time?', 'a' => 'Yes. You can connect accounting, messaging and SMS tools together so different parts of your business stay in sync.'],
        ['q' => 'Will historical data be imported?', 'a' => 'We can help review your current data and advise what can be imported or synced before setup.'],
    ],

    'items' => [
        'zoho-books' => [
            'name' => 'Zoho Books',
            'category' => 'Accounting',
            'logo' => 'assets/zoho.png',
            'color' => '#e4443f',
            'summary' => 'Send daily sales, tax totals, invoices and customer records from SkelApp into Zoho Books.',
            'detail_title' => 'Accounting that stays close to every sale',
            'detail_copy' => 'SkelApp connects with Zoho Books so your sales, payments, expenses and tax records move into accounting without rebuilding reports by hand.',
            'website_url' => 'https://www.zoho.com/books/',
            'hero_image' => 'assets/Moc-lap-phone-02.webp',
            'features' => [
                ['title' => 'Daily sales sync', 'body' => 'Push sales summaries, payment totals and branch activity into Zoho Books for faster reconciliation.'],
                ['title' => 'Cleaner invoices', 'body' => 'Create invoice-ready records from sales and customer data captured at the POS.'],
                ['title' => 'Tax-ready records', 'body' => 'Keep VAT and sales tax data organised so month-end work is easier to review.'],
                ['title' => 'Customer visibility', 'body' => 'Connect buyers, receipts and account activity for a more complete financial view.'],
                ['title' => 'Less manual entry', 'body' => 'Reduce spreadsheet copying between your POS and accounting platform.'],
                ['title' => 'Branch reporting', 'body' => 'Separate sales by shop, register or team so accounting reports are easier to understand.'],
            ],
            'faq' => [
                ['q' => 'Can Zoho Books receive daily summaries?', 'a' => 'Yes. We can configure SkelApp to prepare sales and payment summaries for Zoho Books workflows.'],
                ['q' => 'Can customer data sync too?', 'a' => 'Customer details can be mapped during setup depending on your preferred Zoho Books structure.'],
            ],
        ],
        'xero' => [
            'name' => 'Xero',
            'category' => 'Accounting',
            'logo' => 'assets/xero-logo.png',
            'color' => '#13b5ea',
            'summary' => 'Keep sales, settlements and reporting aligned between SkelApp and Xero.',
            'detail_title' => 'Connect shop sales to Xero reporting',
            'detail_copy' => 'Use SkelApp with Xero to reduce double entry, keep payment totals visible and prepare cleaner sales records for your finance team.',
            'website_url' => 'https://www.xero.com/',
            'hero_image' => 'assets/devicemockup.webp',
            'features' => [
                ['title' => 'Sales summaries', 'body' => 'Send structured daily or branch-level sales summaries for review in Xero.'],
                ['title' => 'Payment matching', 'body' => 'Connect cash, card and mobile-money totals to make reconciliation more predictable.'],
                ['title' => 'Product-level context', 'body' => 'Use POS data to understand what drove your accounting numbers.'],
                ['title' => 'Multi-branch clarity', 'body' => 'Keep location-level activity organised before it reaches finance.'],
                ['title' => 'Audit-friendly records', 'body' => 'Maintain clearer source records for checks, corrections and tax review.'],
                ['title' => 'Month-end speed', 'body' => 'Spend less time collecting sales files from different shops and devices.'],
            ],
            'faq' => [
                ['q' => 'Does SkelApp replace Xero?', 'a' => 'No. SkelApp runs your POS operations, while Xero remains your accounting system.'],
                ['q' => 'Can we choose what data goes to Xero?', 'a' => 'Yes. Data mapping is reviewed during setup so the sync fits your accounting process.'],
            ],
        ],
        'quickbooks' => [
            'name' => 'QuickBooks',
            'category' => 'Accounting',
            'logo' => 'assets/quickbooks.png',
            'color' => '#2ca01c',
            'summary' => 'Connect POS sales and payment records with QuickBooks for cleaner books.',
            'detail_title' => 'QuickBooks records powered by live POS activity',
            'detail_copy' => 'Bring SkelApp sales and payment data into QuickBooks workflows so your finance records stay closer to what happened at the counter.',
            'website_url' => 'https://quickbooks.intuit.com/',
            'hero_image' => 'assets/Moc-tab.webp',
            'features' => [
                ['title' => 'Sales to books', 'body' => 'Move POS sales records toward QuickBooks without waiting for manual reports.'],
                ['title' => 'Payment visibility', 'body' => 'Track cash, cards and mobile-money payment totals from the POS.'],
                ['title' => 'Expense context', 'body' => 'Keep sales and cost activity easier to compare across the business.'],
                ['title' => 'Receipts and invoices', 'body' => 'Use transaction data to support cleaner receipt and invoice records.'],
                ['title' => 'Reporting support', 'body' => 'Give your accountant more reliable data from the point of sale.'],
                ['title' => 'Flexible setup', 'body' => 'Map fields based on your chart of accounts and operating model.'],
            ],
            'faq' => [
                ['q' => 'Can this work with an accountant-managed QuickBooks account?', 'a' => 'Yes. We can coordinate the setup with whoever manages your books.'],
                ['q' => 'Does every sale become a separate entry?', 'a' => 'That depends on your preferred setup. Many businesses choose summaries to keep accounts clean.'],
            ],
        ],
        'sage' => [
            'name' => 'Sage',
            'category' => 'Accounting',
            'logo' => 'assets/sage.png',
            'color' => '#00d639',
            'summary' => 'Link SkelApp sales and retail reports with Sage accounting workflows.',
            'detail_title' => 'Sage-ready sales from every shop',
            'detail_copy' => 'SkelApp helps prepare your retail data for Sage so finance teams can review activity from branches, payment channels and product categories.',
            'website_url' => 'https://www.sage.com/',
            'hero_image' => 'assets/PosSystemRegister.webp',
            'features' => [
                ['title' => 'Branch summaries', 'body' => 'Group sales by shop or register before sending records into accounting.'],
                ['title' => 'Payment breakdowns', 'body' => 'Separate cash, card and mobile-money activity for easier checks.'],
                ['title' => 'Inventory context', 'body' => 'Use POS stock and sales data to support operational reporting.'],
                ['title' => 'Tax support', 'body' => 'Keep tax-sensitive sales information structured from the start.'],
                ['title' => 'Finance handoff', 'body' => 'Give finance cleaner exports and mapped fields instead of raw POS notes.'],
                ['title' => 'Operational control', 'body' => 'Use SkelApp for sales and Sage for accounting without disconnecting the two.'],
            ],
            'faq' => [
                ['q' => 'Can Sage integration support multiple shops?', 'a' => 'Yes. Branch and register mapping can be planned during setup.'],
                ['q' => 'Can SkelApp export data for Sage?', 'a' => 'Yes. Export and sync options depend on your Sage version and workflow.'],
            ],
        ],
        'whatsapp' => [
            'name' => 'WhatsApp',
            'category' => 'Messaging',
            'logo' => 'assets/whatsapp-logo.png',
            'color' => '#25d366',
            'summary' => 'Send order updates, receipts, support messages and customer follow-ups through WhatsApp.',
            'detail_title' => 'Customer conversations connected to your POS',
            'detail_copy' => 'Use WhatsApp with SkelApp to keep customers updated after purchases, send receipts, follow up on orders and support repeat business.',
            'website_url' => 'https://www.whatsapp.com/',
            'hero_image' => 'assets/Mobilehomeview.png',
            'features' => [
                ['title' => 'Digital receipts', 'body' => 'Send customers receipts and purchase confirmations through WhatsApp.'],
                ['title' => 'Order updates', 'body' => 'Keep customers informed when an order is created, prepared or ready.'],
                ['title' => 'Support follow-up', 'body' => 'Move from sale to customer support without losing context.'],
                ['title' => 'Repeat sales', 'body' => 'Use customer history to support better follow-up and re-engagement.'],
                ['title' => 'Team visibility', 'body' => 'Give staff a clearer view of customer requests linked to POS activity.'],
                ['title' => 'Local-first messaging', 'body' => 'Use the channel your customers already understand and check every day.'],
            ],
            'faq' => [
                ['q' => 'Can SkelApp send receipts through WhatsApp?', 'a' => 'Yes. WhatsApp can be used for receipt and order communication workflows.'],
                ['q' => 'Can customers message us back?', 'a' => 'Yes, depending on the WhatsApp setup and support process you choose.'],
            ],
        ],
        'notify-africa-bulksms' => [
            'name' => 'Notify Africa BulkSMS',
            'category' => 'Bulk SMS',
            'logo' => 'assets/notify-logo-bulksms.png',
            'color' => '#1e67ff',
            'summary' => 'Send SMS alerts, promotions, payment reminders and customer updates using Notify Africa BulkSMS.',
            'detail_title' => 'Bulk SMS campaigns from real POS data',
            'detail_copy' => 'Connect SkelApp with Notify Africa BulkSMS to send targeted customer updates, promotions and transactional alerts based on activity in your shop.',
            'website_url' => 'https://notify.africa/',
            'hero_image' => 'assets/CRM-phone-feature.png',
            'features' => [
                ['title' => 'Customer campaigns', 'body' => 'Send promotions to customers based on purchase history and loyalty activity.'],
                ['title' => 'Transactional alerts', 'body' => 'Notify customers about orders, payments or account updates by SMS.'],
                ['title' => 'Bulk reach', 'body' => 'Reach customers even when they are offline or not using smartphone apps.'],
                ['title' => 'Segmented lists', 'body' => 'Build smarter groups from POS customer data for more relevant messaging.'],
                ['title' => 'Performance tracking', 'body' => 'Review campaign activity alongside sales outcomes.'],
                ['title' => 'Local delivery', 'body' => 'Use a messaging provider built for African markets and phone networks.'],
            ],
            'faq' => [
                ['q' => 'Can SMS campaigns use SkelApp customer data?', 'a' => 'Yes. Customer segments can be prepared from SkelApp data before sending campaigns.'],
                ['q' => 'Can SMS be used for order alerts?', 'a' => 'Yes. Transactional alerts can be configured as part of the integration workflow.'],
            ],
        ],
    ],
];
